/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-07-12 15:53:28 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@isilo.db.elephantsql.com:5432/wgvqwqab -t pg_stat_statements -t players -t reviews -t teams -t tours -s public
 *
 */


export namespace pg_stat_statementsFields {
    export type userid = number | null;
    export type dbid = number | null;
    export type queryid = number | null;
    export type query = string | null;
    export type calls = number | null;
    export type total_time = number | null;
    export type min_time = number | null;
    export type max_time = number | null;
    export type mean_time = number | null;
    export type stddev_time = number | null;
    export type rows = number | null;
    export type shared_blks_hit = number | null;
    export type shared_blks_read = number | null;
    export type shared_blks_dirtied = number | null;
    export type shared_blks_written = number | null;
    export type local_blks_hit = number | null;
    export type local_blks_read = number | null;
    export type local_blks_dirtied = number | null;
    export type local_blks_written = number | null;
    export type temp_blks_read = number | null;
    export type temp_blks_written = number | null;
    export type blk_read_time = number | null;
    export type blk_write_time = number | null;

}

export interface pg_stat_statements {
    userid: pg_stat_statementsFields.userid;
    dbid: pg_stat_statementsFields.dbid;
    queryid: pg_stat_statementsFields.queryid;
    query: pg_stat_statementsFields.query;
    calls: pg_stat_statementsFields.calls;
    total_time: pg_stat_statementsFields.total_time;
    min_time: pg_stat_statementsFields.min_time;
    max_time: pg_stat_statementsFields.max_time;
    mean_time: pg_stat_statementsFields.mean_time;
    stddev_time: pg_stat_statementsFields.stddev_time;
    rows: pg_stat_statementsFields.rows;
    shared_blks_hit: pg_stat_statementsFields.shared_blks_hit;
    shared_blks_read: pg_stat_statementsFields.shared_blks_read;
    shared_blks_dirtied: pg_stat_statementsFields.shared_blks_dirtied;
    shared_blks_written: pg_stat_statementsFields.shared_blks_written;
    local_blks_hit: pg_stat_statementsFields.local_blks_hit;
    local_blks_read: pg_stat_statementsFields.local_blks_read;
    local_blks_dirtied: pg_stat_statementsFields.local_blks_dirtied;
    local_blks_written: pg_stat_statementsFields.local_blks_written;
    temp_blks_read: pg_stat_statementsFields.temp_blks_read;
    temp_blks_written: pg_stat_statementsFields.temp_blks_written;
    blk_read_time: pg_stat_statementsFields.blk_read_time;
    blk_write_time: pg_stat_statementsFields.blk_write_time;

}

export namespace playersFields {
    export type id = string;
    export type player_first_name = string;
    export type player_last_name = string;
    export type player_email = string;
    export type player_phone = string;
    export type is_team_owner = boolean;

}

export interface players {
    id: playersFields.id;
    player_first_name: playersFields.player_first_name;
    player_last_name: playersFields.player_last_name;
    player_email: playersFields.player_email;
    player_phone: playersFields.player_phone;
    is_team_owner: playersFields.is_team_owner;

}

export namespace reviewsFields {
    export type id = string;
    export type tour_id = string;
    export type review_title = string;
    export type review_long_text = string | null;
    export type stars = number;

}

export interface reviews {
    id: reviewsFields.id;
    tour_id: reviewsFields.tour_id;
    review_title: reviewsFields.review_title;
    review_long_text: reviewsFields.review_long_text;
    stars: reviewsFields.stars;

}

export namespace teamsFields {
    export type id = string;
    export type team_name = string;
    export type team_number = number;
    export type team_description = string | null;

}

export interface teams {
    id: teamsFields.id;
    team_name: teamsFields.team_name;
    team_number: teamsFields.team_number;
    team_description: teamsFields.team_description;

}

export namespace toursFields {
    export type id = string;
    export type location = string;
    export type tour_title = string;
    export type tour_category = string;
    export type tour_description = string | null;
    export type price = number;
    export type currency = string;
    export type img = Array<string> | null;

}

export interface tours {
    id: toursFields.id;
    location: toursFields.location;
    tour_title: toursFields.tour_title;
    tour_category: toursFields.tour_category;
    tour_description: toursFields.tour_description;
    price: toursFields.price;
    currency: toursFields.currency;
    img: toursFields.img;

}
